name: Deploy to Minikube using GitHub Actions

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Start minikube
        uses: medyagh/setup-minikube@v0.0.10

      - name: Build image
        run: |
          eval $(minikube -p minikube docker-env)
          docker build -f ./Dockerfile -t devopshint/node-app:latest .
          docker images

      - name: Deploy app
        run: kubectl apply -f k8s-node-app.yaml

      - name: Wait for pod ready
        run: |
          kubectl wait --for=condition=Ready pod -l app=nodejs-app --timeout=120s

      - name: Check pods status
        run: kubectl get pods -l app=nodejs-app

      - name: Get pod logs
        run: |
          POD_NAME=$(kubectl get pods -l app=nodejs-app -o jsonpath="{.items[0].metadata.name}")
          kubectl logs $POD_NAME

      - name: Test service URL
        run: |
          minikube service list
          minikube service nodejs-app --url
