name: Deploy to Minikube using GitHub Actions

on: [push]
  
jobs:
  job1:
    runs-on: ubuntu-latest
    name: Build Node.js Docker Image and deploy to Minikube
    steps:
    - uses: actions/checkout@v2

    - name: Start minikube
      uses: medyagh/setup-minikube@master

    - name: Check cluster
      run: kubectl get pods -A

    - name: Build Docker image inside Minikube
      run: |
        export SHELL=/bin/bash
        eval $(minikube -p minikube docker-env)
        docker build -f ./Dockerfile -t devopshint/node-app:latest .
        docker images

    - name: Deploy app to Kubernetes
      run: kubectl apply -f k8s-node-app.yaml

    - name: Test service URL
      run: |
        minikube service list
        minikube service nodejs-app --url
